List album
NoobTalks/crispy-enigma pull request #8
Opened 2021-05-29 00:08 UTC by yxd99

## Summary

- request to external API for get a list albums with the endpoint /albums

## Known Issues

## Trello Card

[https://trello.com/c/vnl6orCZ/30-listado-de-albumes](url)

2021-05-30 14:33 UTC, SOY4RIAS requested changes

2021-05-30 14:33 UTC, SOY4RIAS commented on app/services/album.js
> +    const { data } = await axios.get('https://jsonplaceholder.typicode.com/albums');
this URL should be inside a constant

2021-05-30 14:33 UTC, SOY4RIAS commented on app/controllers/admin.js
> +    const userInfo = await UserService.getUser({ id: tokenDecode.id });
use destructuring

2021-05-30 14:33 UTC, SOY4RIAS commented on app/controllers/admin.js
> +      tokenDecode.role !== userInfo.role
put these conditions inside an array and then

```suggestion
      conditions.some(condition => !!condition)
```

2021-05-30 14:33 UTC, SOY4RIAS commented on app/controllers/admin.js
> +    if (userInfo.role !== 'administrator') {
is better to put this literal value inside a constant

2021-05-30 16:00 UTC, yxd99 commented on app/controllers/admin.js
> +    const userInfo = await UserService.getUser({ id: tokenDecode.id });
I can't unstructured as the properties are declared below (the most relevant that would be the answer), and here it is just to verify identity checking.

2021-06-01 02:04 UTC, SOY4RIAS requested changes

2021-06-01 02:04 UTC, SOY4RIAS commented on app/controllers/admin.js
> +    const userInfo = await UserService.getUser({ id: tokenDecode.id });
Are you sure? cause, I see you use firstName, lastName, role once. so you can avoid using userInfo.{something} maybe email property can create a conflict but you can use an alias

2021-06-01 02:04 UTC, SOY4RIAS commented on app/controllers/album.js
> +    const { error, id, email, firstName, lastName, role } = await UserService.getUser({ id: token.id });
the properties that are used once you don't need to use destructuring on it you can merge email then when used with the function below at line 13

2021-06-01 02:04 UTC, SOY4RIAS commented on app/helpers/utils.js
> +const compareData = (param1, param2) => JSON.stringify(param1) === JSON.stringify(param2);
dont use numbers at variables use something different.

remember to use something in the function that its name indicates its return type value. Eg. a boolean can be with `is` because the answer can be `yes|no` 

```suggestion
const isObjectEqual = (param1, param2) => JSON.stringify(param1) === JSON.stringify(param2);
```

2021-06-01 02:04 UTC, SOY4RIAS commented on app/controllers/admin.js
> +const roleAdmin = 'administrator';
it can be a global constant

2021-06-01 02:04 UTC, SOY4RIAS commented on app/controllers/users.js
> +    const { error, id, firstName, lastName, role, email, password } = await UserService.getUser({
same, you dont need to use destructuring on `id, firstName, lastName, role` you can merge it with `password` and `email` then

2021-06-01 02:04 UTC, SOY4RIAS commented on app/mappers/admin.js
> +    role: 'administrator'
use the constant value

2021-06-01 02:04 UTC, SOY4RIAS commented on app/controllers/album.js
> +      throw errors.unauthorized('Usuario no existe en la DB.');
English pls 😄

2021-06-01 02:04 UTC, SOY4RIAS commented on app/services/user.js
> +      user.password = utils.encryptPassword(user.password);
what happens if there's no password at user 🤔

2021-06-01 02:04 UTC, SOY4RIAS commented on app/services/album.js
> +const albumSupplier = 'https://jsonplaceholder.typicode.com/albums';
consider this as the constant value that can be used even in tests. and use constant naming convention because it is a real constant value

2021-06-01 02:04 UTC, SOY4RIAS commented on test/services/album.test.js
> +    expect(axios.get).toHaveBeenCalledWith('https://jsonplaceholder.typicode.com/albums');
as I said. this endpoint value can be used on tests

2021-06-01 23:01 UTC, SOY4RIAS requested changes

2021-06-01 23:01 UTC, SOY4RIAS commented on app/controllers/admin.js
> +    const { error, password, ...user } = await UserService.getUser({ id: token.id });
you can add a parameter to pass the fields you need to omit, or just use delete user.password.

I prefer the first option

2021-06-01 23:01 UTC, SOY4RIAS commented on app/controllers/album.js
> +    const { error, password, ...user } = await UserService.getUser({ id: token.id });
same, omit field

2021-06-01 23:01 UTC, SOY4RIAS commented on app/helpers/constants.js
> +exports.ALBUM_SUPPLIER = 'https://jsonplaceholder.typicode.com/albums';
constants should be inside app folder

2021-06-02 02:59 UTC, SOY4RIAS requested changes

2021-06-02 02:59 UTC, SOY4RIAS commented on app/controllers/album.js
> +    }
this should be a middleware 😄

2021-06-02 02:59 UTC, SOY4RIAS commented on app/controllers/admin.js
>      }
this should be a different middleware

2021-06-02 02:59 UTC, SOY4RIAS commented on app/controllers/admin.js
> +      throw errors.unauthorized('User does not exist in the DB.');
dont forget to change this 😄

2021-06-02 03:56 UTC, SOY4RIAS requested changes

2021-06-02 03:56 UTC, SOY4RIAS commented on app/middlewares/validators/user.js
> +    req.user = user;
```suggestion
    res.locals.user = user;
```
FYI http://expressjs.com/en/api.html#res.locals

2021-06-02 03:56 UTC, SOY4RIAS commented on app/middlewares/validators/user.js
> +    const { role, email } = req.user;
idem `res.locals.user`

2021-06-02 03:56 UTC, SOY4RIAS commented on app/middlewares/validators/user.js
> +const validateIdentity = async (req, res, next) => {
validateAuthentication?

2021-06-02 03:56 UTC, SOY4RIAS commented on app/routes.js
> +  app.post('/admin/users', [validateToken, validateSignUpDTO, validateIdentity, isAdmin], signUpAdmin);
first, validate the current session

2021-06-02 04:31 UTC, SOY4RIAS approved these changes

2021-06-02 04:31 UTC, SOY4RIAS commented on app/constants.js
> +exports.TOKEN = 'token';
```suggestion
exports.AUTH_HEADER = 'Authorization';
```

2021-06-02 04:58 UTC, merged